alias exa='exa --icons'
alias update='sudo pacman -Syu --noconfir;yay -Syu;pkill -RTMIN+4 i3blocks;sudo bash ~/Documents/Code/Config/change-mimeinfo.sh'
alias depos-clean='sudo pacman -Sc;yay -Sc'
alias remove-non_used-repos='echo "only as root";pacman -Qqd | pacman -Rsu -;pacman -Qtdq | pacman -Rns -'
#alias tlmgr='/usr/share/texmf-dist/scripts/texlive/tlmgr.pl --usermode'
