#!/usr/bin/env sh

case $BLOCK_BUTTON in
    1) pactl set-source-mute @DEFAULT_SOURCE@ toggle ;;
esac

# If mic is muted
if [[ "$(pactl list sources | grep Mute | awk '{print $2}' | grep yes)" == "yes" ]]
then
    echo "  "
else
    echo "  "
fi
