#!/usr/bin/env sh

case $BLOCK_BUTTON in
    1) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
esac

function vol() {
    pactl list sinks \
    | awk '/^[[:space:]]Volume:/ { if (++n == '$(( $SINK + 1 ))') print $5 }' \
    | tr -d '%'
}

# If volume is muted
if [ "$(pactl list sinks | awk '/Mute:/ {print $2}')" = "yes" ]; then
    echo "🔇Mute"
    exit 0
fi

v=$(vol)
if [ "$v" -gt "100" ]; then
    echo " $v%"
elif [ "$v" -gt "0" ] && [ "$v" -lt "50" ]; then
    echo "🔉$v%"
else
    echo "🔊$v%"
fi
